ALTER TABLE Book DROP CONSTRAINT FK_Book_CATALOG_ID
ALTER TABLE AUTHOR_BOOK DROP CONSTRAINT FK_AUTHOR_BOOK_listBooks_ID
ALTER TABLE AUTHOR_BOOK DROP CONSTRAINT FK_AUTHOR_BOOK_listAuthor_ID
DROP TABLE Book CASCADE
DROP TABLE AUTHOR CASCADE
DROP TABLE Catalog CASCADE
DROP TABLE AUTHOR_BOOK CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
